
DROP TABLE AIP.ADMIN;
CREATE table AIP.ADMIN (
    ID          INTEGER NOT NULL 
                PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1),
    USERNAME    VARCHAR(255)NOT NULL UNIQUE, 
    PASSWORD    VARCHAR(255)NOT NULL,
    FULLNAME    VARCHAR(255)NOT NULL,
    EMPLOYEEID  VARCHAR(255)NOT NULL UNIQUE,
    EMAIL       VARCHAR(255)NOT NULL);
